name: Build and Test

on:
  push:
    branches:
      - feature/lab2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          wget https://download.java.net/java/GA/jdk18/7863447f0ab643c585b9bdebf67c69db/4/GPL/openjdk-18_linux-x64_bin.tar.gz
          tar xzf openjdk-18_linux-x64_bin.tar.gz
          sudo mv jdk-18 /usr/local/
          echo 'export JAVA_HOME=/usr/local/jdk-18' >> $GITHUB_ENV
          echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $GITHUB_ENV

      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test
