name: Build and Test

on:
  push:
    branches:
      - feature/lab2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '18'

      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test
